controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController

joint_group_position_controller:
  ros__parameters:
    joints:
      - shoulder_yaw_joint
      - shoulder_pitch_joint
      - elbow_pitch_joint
      - wrist_pitch_joint
      - wrist_roll_joint

    command_interfaces:
      - position

    state_interfaces:
      - position